feat(09-Functions)

diff --git a/.github/workflows/09-functions.yaml b/.github/workflows/09-functions.yaml
--- a/.github/workflows/09-functions.yaml
+++ b/.github/workflows/09-functions.yaml
@@ -19,8 +19,8 @@ jobs:
       run: "I am a bug fix"
     - name: Sleep for 20 seconds
       run: sleep 20
-    - name: Failing step
-      run: exit 1
+    # - name: Failing step
+    #   run: exit 1
     - name: I will be skipped
       if: ${{ success() }}
       run: echo "I will print if previous steps succeed."
